services:
  # Backend (Spring Boot API)
  api:
    build:
      context: ./api-auditoria
      dockerfile: Dockerfile
    container_name: auditoria-api
    env_file: .env.production
    ports:
      - "8080:8080"
    networks:
      - auditoria-network
    restart: always

  # Frontend (Angular + Nginx)
  frontend:
    build:
      context: ./front-auditoria
      dockerfile: Dockerfile.frontend
      args:
        CONFIGURATION: production
    container_name: auditoria-frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - auditoria-network
    restart: always

networks:
  auditoria-network:
    driver: bridge
