services:
  # Backend (Spring Boot API)
  api:
    build:
      context: ./api-auditoria
      dockerfile: Dockerfile
    container_name: auditoria-api
    env_file: .env.production
    network_mode: host
    restart: always

  # Frontend (Angular + Nginx)
  frontend:
    build:
      context: ./front-auditoria
      dockerfile: Dockerfile.frontend
      args:
        CONFIGURATION: production
    container_name: auditoria-frontend
    network_mode: host
    depends_on:
      - api
    restart: always
