input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [logger_name] =~ /auth/ {
    mutate {
      add_tag => ["authentication"]
    }
  }

  if [message] =~ /risk/ or [message] =~ /risco/ {
    mutate {
      add_tag => ["risk-analysis"]
    }
  }

  if [message] =~ /blockchain/ or [message] =~ /Blockchain/ {
    mutate {
      add_tag => ["blockchain"]
    }
  }

  if [level] == "ERROR" or [level] == "WARN" {
    mutate {
      add_tag => ["alert"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "auth-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
